# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  _10k-dat-ubuntu16-GCC5:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: ubuntu:16.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: basic check
          command: cat /etc/os-release; pwd; ls -alh; ls ~ -alh
      # - run:
      #     name: install preqs
      #     command: apt update; apt install software-properties-common -y; add-apt-repository ppa:ubuntu-toolchain-r/test -y; apt update; apt install wget make gcc-9 g++ gfortran -y; gfortran -v
      - run:
          name: install preqs
          command: apt update; apt install wget make gcc g++ gfortran -y; gfortran -v
      # - run:
      #     name: configure
      #     command: export FCFLAGS="-g -O0 -fcheck=all -Wall"; export CFLAGS=$FCFLAGS; export CXXFLAGS=$FCFLAGS; ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      - run:
          name: configure
          command: ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      - run:
          name: make
          command: make clean; make -j
      - run:
          name: generate test dir and ini file
          command: >
            mkdir autotest;
            cp -p ./build/nbody6++* ./autotest/;
            cd autotest;
            wget https://github.com/kaiwu-astro/garage/raw/main/Nbody6ppGPU-inputfile/kai_10k/10k.test;
            wget https://github.com/kaiwu-astro/garage/raw/main/Nbody6ppGPU-inputfile/kai_10k/dat.10;
            pwd; ls -alh
      - run:
          name: run simulation
          command: ulimit -s unlimited; cd autotest; export OMP_NUM_THREADS=32; export execname=`ls nbody6++*`; ./$execname < 10k.test
  _1k-no-dat-ubuntu16-GCC5:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: ubuntu:16.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: basic check
          command: cat /etc/os-release; pwd; ls -alh; ls ~ -alh
      # - run:
      #     name: install preqs
      #     command: apt update; apt install software-properties-common -y; add-apt-repository ppa:ubuntu-toolchain-r/test -y; apt update; apt install wget make gcc-9 g++ gfortran -y; gfortran -v
      - run:
          name: install preqs
          command: apt update; apt install wget make gcc g++ gfortran -y; gfortran -v
      # - run:
      #     name: configure
      #     command: export FCFLAGS="-g -O0 -fcheck=all -Wall"; export CFLAGS=$FCFLAGS; export CXXFLAGS=$FCFLAGS; ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      - run:
          name: configure
          command: ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      - run:
          name: make
          command: make clean; make -j
      - run:
          name: generate test dir and ini file
          command: >
            mkdir autotest;
            cp -p ./build/nbody6++* ./autotest/;
            cd autotest;
            wget https://github.com/kaiwu-astro/garage/raw/main/Nbody6ppGPU-inputfile/kai_1k_no_dat-10/1k.inp;
            pwd; ls -alh
      - run:
          name: run simulation
          command: >
            ulimit -s unlimited;
            cd autotest;
            export OMP_NUM_THREADS=32;
            export execname=`ls nbody6++*`;
            ./$execname < 1k.inp
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-simulation:
    jobs:
      - _10k-dat-ubuntu16-GCC5
      - _1k-no-dat-ubuntu16-GCC5
